name: Gerar JSON das imagens

on:
  push:
    branches:
      - main  # ou a branch que você quiser
  workflow_dispatch:  # permite rodar manualmente

jobs:
  gerar-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Rodar script para gerar JSON
        run: node gerar-json-imagens.js

      - name: Commit e push do imagens.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add imagens.json
          git commit -m "Atualizar imagens.json automaticamente"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
